version: "3.9"

services:
  torchrl:
    container_name: torchrl
    image: torchrl
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - USERNAME=dexter
        - UID=${UID:-1000}
        - GID=${UID:-1000}

    network_mode: "host"
    pid: "host"
    tty: true
    privileged: true
    
    environment:
      - USERNAME=dexter
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    
    volumes:
      - ../src:/home/dexter/programming/${workspaceFolderBasename}:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      

  